version: "3"

networks:
  lan:

services:
  farmaturno:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: farmaturno
    working_dir: /usr/src
    command: ["netlify", "dev", "-c", "npm start", "--target-port", "1313"]
    environment:
      NODE_ENV: development
      REACT_APP_MAPBOX_TOKEN: ${REACT_APP_MAPBOX_TOKEN}
      FT_AWS_ACCESS_KEY_ID: ${FT_AWS_ACCESS_KEY_ID}
      FT_AWS_SECRET_ACCESS_KEY: ${FT_AWS_SECRET_ACCESS_KEY}
      FT_AWS_REGION: ${FT_AWS_REGION}
    networks:
      - lan
    ports:
      - "1313:1313"
      - "8888:8888"
    volumes:
      - ./app:/usr/src/
