version: "3"

networks:
  lan:

services:
  farmaturno:
    image: node:16-alpine
    container_name: farmaturno
    working_dir: /usr/src
    command: ["npm", "start"]
    environment:
      NODE_ENV: development
      REACT_APP_FIREBASE_APIKEY: ${REACT_APP_FIREBASE_APIKEY}
      FT_AWS_ACCESS_KEY_ID: ${FT_AWS_ACCESS_KEY_ID}
      FT_AWS_SECRET_ACCESS_KEY: ${FT_AWS_SECRET_ACCESS_KEY}
      FT_AWS_REGION: ${FT_AWS_REGION}
    networks:
      - lan
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/
